### ISSUE TITLE
Error launching RStudio and installing rmarkdown package

### ISSUE THREAD

**Issue by TVK36692** [DS4PS/cpp-526-fall-2019#1]
When I launch R studio or try to install the rmarkdown package i get the following error:

"Warning message:
In normalizePath(path.expand(path), winslash, mustWork) :
  path[1]="//Afwfs/AF/Users/tkemper/My Documents/R/win-library/3.6": An unexpected network error occurred"

What should i change?

**Comment by lecy** [comment]
Hi TVK -

This is caused by a lack of permissions to read or write to the R folder at:

`//Afwfs/AF/Users/tkemper/My Documents/R/win-library/3.6`

Is this a network (shared drive) folder? Is it a folder that all users on your computer can access? 

Mine looks like this: `"C:/Users/jdlecy/Documents"`

This makes me suspect your have it installed in some network or shared folder. What comes before //Wfwfs/? 

It's an R problem, not an R studio problem. I suggest uninstalling R, and when you install it again put it in a root directory (close to C:) on your computer. 

It could be several other things related to your version of windows and some other settings, but that is the easiest place to start so try that first, please.

**Comment by lecy** [comment]
Were you able to get it working?

**Comment by TVK36692** [comment]
Hi, thank you for your quick response. I was travelling for work and had a VPN connection. I just got home and uninstalled/reinstalled R and RStudio. I was then able to get the rmarkdown package to install correctly. Any advice what to try next?

**Comment by lecy** [comment]
I would dive into the lab:

https://ds4ps.org/cpp-526-fall-2019/labs/lab-01-instructions.html

And focus on these three chapters for content:

http://ds4ps.org/dp4ss-textbook/ch-033-calculator.html
http://ds4ps.org/dp4ss-textbook/ch-040-functions.html
http://ds4ps.org/dp4ss-textbook/ch-050-vectors.html
